name: Release

on:
  push:
    branches:
      - main
    paths:
      - "browser-extension-dist/**"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - run: |
          zip -r browser-extension-dist.zip browser-extension-dist

      - name: Read version name from manifest.json
        id: version
        run: |
          echo "version_name=$(cat browser-extension-dist/manifest.json | jq -r '.version_name')" >> "$GITHUB_OUTPUT"

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{steps.version.outputs.version_name}}

      - uses: softprops/action-gh-release@v2
        with:
          files: browser-extension-dist.zip
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
